darknet_ros:
  ros__parameters:
    yolo_model:
      config_file:
        name: yolo-fastest.cfg
      weight_file:
        name: yolo-fastest.weights
      threshold:
        value: 0.3
      detection_classes:
        names:
          - aeroplane
          - bicycle
          - bird
          - boat
          - bottle
          - bus
          - car
          - cat
          - chair
          - cow
          - diningtable
          - dog
          - horse
          - motorbike
          - person
          - pottedplant
          - sheep
          - sofa
          - train
          - tvmonitor
