darknet_ros:
  ros__parameters:
    yolo_model:
      config_file:
        name: yolo-fastest.cfg
      weight_file:
        name: yolo-fastest.weights
      threshold:
        value: 0.3
      detection_classes:
        names:
          - Laeroplane
          - Lbicycle
          - Lbird
          - Lboat
          - Lbottle
          - Lbus
          - Lcar
          - Lcat
          - Lchair
          - Lcow
          - Ldiningtable
          - Ldog
          - Lhorse
          - Lmotorbike
          - Lperson
          - Lpottedplant
          - Lsheep
          - Lsofa
          - Ltrain
          - Ltvmonitor
